/// Flutter icons FatigueTest
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FatigueTest
///      fonts:
///       - asset: fonts/FatigueTest.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
///
import 'package:flutter/widgets.dart';

class FatigueTest {
  FatigueTest._();

  static const _kFontFam = 'FatigueTest';
  static const String? _kFontPkg = null;

  static const IconData calendarOutline = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dialpad = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kingBed = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData listAlt = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helpDesk = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarmOn = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData detail = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drawer = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
